import type { Metadata } from "next";
import "./styles/globals.scss";

export const metadata: Metadata = {
  title: "The Daily Orbit",
  description: "Generated by Alyssa Sharpe",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {children}
      </body>
    </html>
  );
}
